baseURL = "https://arnabsanyal.github.io/website/"
# baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"
publishDir = "docs"

[params]
    title = "Arnab Sanyal"
    author = "Arnab Sanyal"
    description = "Research Website"
    footer_image = "frame.png"

    # Profile section
    [params.profile]
        name = "Arnab Sanyal"
		tagline = "Graduate Research Assistant at The University of Southern California"
		location = "Los Angeles, California"
        photo = "profile.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        class = "fab"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/arnabsanyal17/"
        title = "LinkedIn"
		
        [[params.social.list]]
        class = "fab"
        icon = "fa-stack-overflow"
        url = "https://stackoverflow.com/users/7517511/arnab-sanyal"
        title = "StackOverflow"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/arnabsanyal"
        title = "GitHub"

        [[params.social.list]]
        class = "fab"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/lonewolf1898"
        title = "Facebook"
		
	[[params.social.list]]
        class = "ai"
        icon = "ai-google-scholar"
        url = "https://scholar.google.com/citations?user=vUC7-ygAAAAJ"
        title = "Google Scholar"
		
	[[params.social.list]]
        class = "fab"
        icon = "fa-medium-m"
        url = "https://medium.com/@arnabsanyal_15738"
        title = "Medium"	

  [[params.social.list]]
        class = "ai"
        icon = "ai-orcid"
        url = "https://orcid.org/0000-0001-6365-6769"
        title = "Orcid"

	[[params.social.list]]
	class = "ai"
	icon = "ai-cv"
	url = "https://drive.google.com/open?id=1RMrdG27K67UBXrz6XmN4FziB4Aj9k5WD"
	title = "Resume"
	
	[[params.social.list]]
	class = "fas"
	icon = "fa-envelope"
	url = "mailto:arnab.sanyal@usc.edu"
	title = "Electronic mail"

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "M.S. in Computer Science"
        link = "https://catalogue.usc.edu/preview_program.php?catoid=11&poid=10897&returnto=3699"
        college = "University of Southern California"
        dates = "2017 - present"
	    credits = "24/28"
        p1 = "**Fully funded by Ming Hsieh Department of ECE graduate assistantship**"

        [[params.education.list]]
        degree = "M.S. in Electrical & Computer Engineering"
        link = "https://catalogue.usc.edu/preview_program.php?catoid=11&poid=10911&returnto=3756"
        college = "University of Southern California"
        dates = "2017 - present"
	    credits = "25/28"
        p1 = "**Fully funded by Ming Hsieh Department of ECE graduate assistantship**"
        p2 = "Completed PhD-level coursework"
        p3 = "Masters with a research focus in machine-learning (1 publication)"

	      [[params.education.list]]
        degree = "B.Tech. (Hons.) in Electrical Engineering with M.Tech. in Instrumentation and Signal Processing Engineering (Progressive Dual Degree)"
        college = "Indian Institute of Technology, Kharagpur"
        link = "https://erp.iitkgp.ac.in/ERPWebServices/curricula/CurriculaSubjectsList.jsp?stuType=UG&splCode=EE5"
        dates = "2012 - 2017"
	      minor = "Electronics & Electrical Communications Engineering"
	      micro = "Embedded Wireless Systems (GSSST - IIT Kharagpur)"
        credits = "263"
        gpa = "8.11/10"
        p1 = "**Ranked 2551 (99.47 percentile nationwide)** in IIT JEE Examination, April 2012."
        p2 = "Received M.C.M. scholarship for the duration of the first four years."
        p3 = "Changed department with a GPA of 9.16 at the end of 2<sup>nd</sup> semester. (**Top 5 percentile** , 67 out of 1332, could achieve this in July 2013)"
        p4 = "Finally **ranked 5** out of 18 students from same degree specialzation batch"

    # Hobbies section
    [params.hobbies]
        title = "Hobbies"
		
        [[params.hobbies.list]]		
		hobby = "**Cooking**"
        icon = "fas fa-utensils"
		
        [[params.hobbies.list]]		
		hobby = "**Adventures** - Hiking, Biking, Backpacking and Exploration"
        icon = "fas fa-hiking"

        [[params.hobbies.list]]		
		hobby = "**Sports** - Soccer, Badminton, Table Tennis, Volleyball, Swimming"
        icon = "fas fa-volleyball-ball"

	    [[params.hobbies.list]]
		hobby = "**Television** - Action, Adventure, Thriller, Mystery, Crime"
        icon = "fa fa-tv"

        [[params.hobbies.list]]
        hobby = "**Video Games**"
        icon = "fas fa-gamepad"


    # Publication section
    [params.publication]
        title = "Publications"

        [[params.publication.list]]
        title = "Neural Network Training with Approximate Logarithmic Computations"
        authors = "**Arnab Sanyal**, Peter A. Beerel, Keith M. Chugg"
        date = "2019"
        journal = " in IEEE International Conference on Acoustics, Speech, and Signal Processing"
        journal_abbvr = "ICASSP 2020"
        link = "#"
        link_bib = "./bib/Sanyal_neural2019.bib"
        link_pdf = "./pdf/Sanyal_neural2019.pdf"
        link_arx = "https://arxiv.org/abs/1910.09876"
        link_blg = "https://towardsdatascience.com/neural-networks-training-with-approximate-logarithmic-computations-44516f32b15b"
        link_git = "https://github.com/arnabsanyal/lnsdnn"
    
    # Journal modal pop-ups
    [params.icassp]
        title = "IEEE ICASSP"
        date = "2020"
        hindex = "80"
        hmedian = "140"
        ranking_idx1 = "#1 (overall)"
        ranking_idx1_name = "Acoustics & Sound"
        ranking_idx1_link = "https://scholar.google.com/citations?view_op=top_venues&hl=en&venue=HHC6AUo36fEJ.2019&vq=phy_acousticssound"
        ranking_idx2 = "#4 (overall) and #1 (conferences only)"
        ranking_idx2_name = "Signal Processing"
        ranking_idx2_link = "https://scholar.google.com/citations?view_op=top_venues&hl=en&venue=HHC6AUo36fEJ.2019&vq=eng_signalprocessing"
        descript = "World’s largest and most comprehensive technical conference focused on signal processing and its applications."
        location = "Barcelona, Spain"
        map_link = "https://goo.gl/maps/KL5aYvwPKK7JKTiw8"

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Experience"

        [[params.jobs.list]]
        position = "**Graduate Research Assistant** - Dept. of Electrical & Computer Engg."
        dates = "May 2018 - present"
        link = "http://graduateschool.usc.edu/"
        company = "Graduate School, U.S.C."
        p1 = "Worked at [Hardware Accelerated Learning](https://hal.usc.edu/) group"
        p2 = "Area of Research - Algorithm and Architecture Design for Neural Networks Training on Accelerators"
        p3 = "Published in top signal processing conference"

        [[params.jobs.list]]
        position = "**Graduate Teaching Assistant** - Dept. of Electrical & Computer Engg."
        dates = "Aug 2017 - present"
        link = "http://graduateschool.usc.edu/"
        company = "Graduate School, U.S.C."
        p1 = "Teaching Assistant for 8 courses over 8 semesters"

        [[params.jobs.list]]
        position = "**Graduate Research Assistant** - Dept. of Electrical & Computer Engg."
        dates = "Aug 2017 - May 2018"
        link = "http://graduateschool.usc.edu/"
        company = "Graduate School, U.S.C."
        p1 = "Worked in [Project SHARP](https://sites.usc.edu/projectsharp/)"
        p2 = "Worked on graph theory problems like PageRank, NxContingency, graph embedding and belief propagation" 

        [[params.jobs.list]]
        position = "**Teaching Assistant** - Dept. of Electrical Engineering"
        dates = "Jan 2016 - Apr 2017"
        link = "http://www.ee.iitkgp.ac.in/"
        company = "Indian Institute of Technology, Kharagpur"
        p1 = "Teaching Assistant for 3 courses during a period of 3 semesters"

        [[params.jobs.list]]
        position = "**Undergraduate Research Assistant** - Dept. of Computer Science"
        dates = "Jul 2015 - Apr 2017"
        link = "http://cse.iitkgp.ac.in/"
        company = "Indian Institute of Technology, Kharagpur"
        p1 = "Researched at [Secured Embedded Architecture Laboratory](http://cse.iitkgp.ac.in/resgrp/seal/)"
        p2 = "Software Acceleration of novel Reversible Watermarking Algorithms"
        p3 = "Accelerator architecture design on FPGA"

        [[params.jobs.list]]
        position = "**Sofware Engineering Intern** - Linux Perf. Team"
        dates = "May 2016 - Jul 2016"
	    link = "https://www.qualcomm.com/company/locations/india"
        company = "Qualcomm India Private Ltd."
        p1 = "Designed an Android system app for Testing and Benchmarking Systems"

        [[params.jobs.list]]
        position = "**Sofware Engineering Intern** - Linux Kernel Team"
        dates = "May 2015 - Jul 2015"
	    link = "https://www.qualcomm.com/company/locations/india"
        company = "Qualcomm India Private Ltd."
        p1 = "Implemented a Memory Crawler app for Linux on python"
        p2 = "Simulated a Smart Traffic Grid on Sumo (coded in python)"

    # About Section
    [params.about]
        icon = "fa fa-user"
        title = "About"

        [[params.about.list]]
        bio = "My name is Arnab Sanyal. I completed my five-year Bachelors and Masters Dual Degree in Electrical Engineering from IIT Kharagpur. Currently I am a graduate student at University of Southern California. I am researching Deep Learning training algorithms trying to make them less compute intensive and more suited for hardware accelerators."
        
        [[params.about.interest.list]]
        name = "Deep Learning Training Algorithms"

        [[params.about.interest.list]]
        name = "Computation/Energy Reduction in Training/Inference"

        [[params.about.interest.list]]
        name = "AI Accelerator Design"

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Projects"

        [[params.projects.list]]
        title = "Accelerating Neural Network Training with Approximate Computations"
        url = "#"
        dates = "Jan 2018 - present"
        location = "University of Southern California, Los Angeles"
        description = "As a Graduate Research Assistant, I contribute to the [HAL research project](https://hal.usc.edu/). My work up to now has been focussed on exploring novel algorithmic solutions to achieve DeepLearning on hardware. Mostly I try to achieve training on DL accelerators with less amount of computations"
		
        [[params.projects.list]]
        title = "Hardware-Software co-design to accelerate Watermarking Algorithms"
        url = "#"
        dates = "Jul 2015 - Apr 2017"
        location = "Indian Institute of Technology, Kharagpur"
        description = "My research focus at [SEAL](http://cse.iitkgp.ac.in/resgrp/seal/) was on optimizations, both at hardware and software level to accelerate Reversible Watermarking Algorithms"

    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]
        skill = "Python, C, Java, C++, MATLAB, Shell, AVR Assembly, HPC (OpenMP), LATEX"
        skillrating = 90
                
        [[params.skills.list]]
        skill = "R, GNU Octave, ARM Assembly, Android, Verilog, MIPS Assembly, Cuda"
        skillrating = 80
		
        [[params.skills.list]]
        skill = "Scala, HTML, CSS, PHP"
        skillrating = 60

    # Languages section
    [params.languages]
        icon = "fa-language"
        title = "Languages"

        [[params.languages.list]]
        language = "English, Bengali"
        languagerating = 95
                
        [[params.languages.list]]
        language = "Hindi"
        languagerating = 75
    
        [[params.languages.list]]
        language = "Deutsch"
        languagerating = 45

        [[params.languages.list]]
        language = "Italiano, Español"
        languagerating = 20

    # Teaching section
    [params.teaching]
        title = "Teaching"
        
        [[params.teaching.list]]     
        subject = "EE30004: Embedded Systems"
        sem = "Spr. 2016"
        role = "Undergrad. Shadow Mentor"
        loc = "IIT Kharagpur"

        [[params.teaching.list]]     
        subject = "EE11001: Electrical Technology Lab"
        sem = "Fall 2016"
        role = "Grad. Teaching Assistant"
        loc = "IIT Kharagpur"

        [[params.teaching.list]]     
        subject = "EE11001: Electrical Technology Lab"
        sem = "Spr. 2017"
        role = "Grad. Teaching Assistant"
        loc = "IIT Kharagpur"

        [[params.teaching.list]]     
        subject = "CSCI356: Intro. to Computer Systems"
        sem = "Fall 2017"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"

        [[params.teaching.list]]     
        subject = "EE599: Software Design & Optimization for Electrical Engineers"
        sem = "Spr. 2018"
        role = "Grad. Student Mentor"
        loc = "USC Los Angeles"

        [[params.teaching.list]]     
        subject = "CSCI350: Intro. to Operating Systems"
        sem = "Sum. 2018"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"

        [[params.teaching.list]]     
        subject = "EE109L: Intro. to Embedded Systems"
        sem = "Fall 2018"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"

        [[params.teaching.list]]     
        subject = "EE599: Deep Learning"
        sem = "Spr. 2019"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"
        
        [[params.teaching.list]]     
        subject = "CSCI350: Intro. to Operating Systems"
        sem = "Sum. 2019"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"
        
        [[params.teaching.list]]     
        subject = "CSCI350: Intro. to Operating Systems"
        sem = "Fall 2019"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"

        [[params.teaching.list]]     
        subject = "EE599: Deep Learning"
        sem = "Spr. 2020"
        role = "Grad. Teaching Assistant"
        loc = "USC Los Angeles"
        
